# Form implementation generated from reading ui file 'coolExample.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 198)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread: pad, x1:0, y1:0, x2:1, y2:1, stop: 0 rgba(2,0,36,1), stop: 1  rgba(9,39,121,1));")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 10, 551, 41))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: rgb(5, 5, 5);\n"
"    border-radius: 10px;\n"
"    border-style: solid;\n"
"    text-align: center;\n"
"    font: 14pt \"Arial\";\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread: pad, x1:0, y1:0, x2:1, y2:1, stop: 0 rgba(185, 105, 254, 255), stop: 1  rgba(106, 211, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setValue(75)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 60, 231, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread: pad, x1:0, y1:0, x2:1, y2:1, stop: 0 rgba(185, 105, 254, 255), stop: 1  rgba(106, 211, 255, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread: pad, x1:0, y1:0, x2:1, y2:1, stop: 0 rgba(255, 98, 0, 255), stop: 1  rgba(253, 183, 119, 255));\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-width : 1.2px;\n"
"    border-style:inset;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        
        
        
# ----------------------------------------------------------------------------------------
import sys
from PyQt6.QtWidgets import QApplication, QWidget
import time

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent=parent)
        ui = Ui_MainWindow()
        ui.setupUi(self)
        


import sys

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec())
